# Generated by Django 2.1.7 on 2019-03-28 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='classes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='API_register.Classes'),
        ),
    ]
