# Generated by Django 2.1.7 on 2019-03-28 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_register', '0002_auto_20190328_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='classes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='API_register.Classes'),
        ),
    ]
