# Generated by Django 2.1.7 on 2019-03-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_register', '0003_auto_20190328_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcements',
            old_name='deleted',
            new_name='hidden',
        ),
    ]
